name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm i
          npm run build
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: dist
      #     CLEAN: true
      - name: 发布到Coding
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REF: 'github.com/songxingguo/hi.git'
          CO_TOKEN: ${{ secrets.CO_TOKEN }}
          CO_REF: 'e.coding.net/songxingguo/songxingguo.coding.me/hi.git'
        run: |
          cd ./dist
          git init
          git config user.name "songxingguo"
          git config user.email "1328989942@qq.com"
          git add .
          git commit -m "Update Blog By GithubAction With Build $TRAVIS_BUILD_NUMBER"
          # Github Pages
          git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
          # Coding Pages
          git push --force --quiet "https://zrUWsPQJyF:${CO_TOKEN}@${CO_REF}" master:master